/**
 * System Constants for Aarogya Adaptive OPD Queue & Patient Continuity System
 * Team AstraBytes
 */

const ROLES = {
  PATIENT: 'PATIENT',
  STAFF: 'STAFF',
  DOCTOR: 'DOCTOR',
  ADMIN: 'ADMIN'
};

const TOKEN_TYPES = {
  ONLINE: 'ONLINE',
  PAPER: 'PAPER',
  EMERGENCY: 'EMERGENCY'
};

const TOKEN_STATUS = {
  WAITING: 'WAITING',
  CALLED: 'CALLED',
  IN_CONSULTATION: 'IN_CONSULTATION',
  COMPLETED: 'COMPLETED',
  NO_SHOW: 'NO_SHOW',
  TEMPORARILY_SKIPPED: 'TEMPORARILY_SKIPPED',
  RE_ENTRY_PENDING: 'RE_ENTRY_PENDING',
  CANCELLED: 'CANCELLED'
};

const QUEUE_EVENTS = {
  TOKEN_CREATED: 'TOKEN_CREATED',
  PAPER_TOKEN_CREATED: 'PAPER_TOKEN_CREATED',
  EMERGENCY_ADDED: 'EMERGENCY_ADDED',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  PATIENT_CALLED: 'PATIENT_CALLED',
  CONSULTATION_STARTED: 'CONSULTATION_STARTED',
  CONSULTATION_COMPLETED: 'CONSULTATION_COMPLETED',
  DOCTOR_DELAYED: 'DOCTOR_DELAYED',
  DOCTOR_EARLY_FINISH: 'DOCTOR_EARLY_FINISH',
  NO_SHOW: 'NO_SHOW',
  TEMPORARY_SKIP: 'TEMPORARY_SKIP',
  SMART_REENTRY: 'SMART_REENTRY',
  TOKEN_CANCELLED: 'TOKEN_CANCELLED',
  QUEUE_OVERRIDE: 'QUEUE_OVERRIDE',
  NO_MAJOR_CHANGE: 'NO_MAJOR_CHANGE'
};

const PAYMENT_STATUS = {
  NOT_REQUIRED: 'NOT_REQUIRED',
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

const NOTIFICATION_CHANNELS = {
  SMS: 'SMS',
  IVR: 'IVR',
  WEB: 'WEB'
};

const NOTIFICATION_TYPES = {
  OTP: 'OTP',
  TOKEN_CONFIRMATION: 'TOKEN_CONFIRMATION',
  ETA_UPDATE: 'ETA_UPDATE',
  TURN_APPROACHING: 'TURN_APPROACHING',
  NO_SHOW_REMINDER: 'NO_SHOW_REMINDER',
  EMERGENCY_DELAY_ALERT: 'EMERGENCY_DELAY_ALERT',
  CONSULTATION_COMPLETE: 'CONSULTATION_COMPLETE'
};

const DEFAULT_CONFIG = {
  AVERAGE_CONSULTATION_DURATION: 8, // minutes
  NO_SHOW_GRACE_PERIOD_MINUTES: 10,
  ETA_NOTIFICATION_THRESHOLD_MINUTES: 5, // minimum change to notify patient
  TURN_APPROACHING_THRESHOLD_MINUTES: 10,
  RE_ENTRY_POLICY: 'NEXT_AVAILABLE_AFTER_CURRENT', // or 'END_OF_QUEUE'
  TIMEZONE: 'Asia/Kolkata'
};

module.exports = {
  ROLES,
  TOKEN_TYPES,
  TOKEN_STATUS,
  QUEUE_EVENTS,
  PAYMENT_STATUS,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_TYPES,
  DEFAULT_CONFIG
};
